import './battle/BattleEngineBaseEdgeCompat.js';
import './ui/BattleRoomExact.css';
import './ui/BattleRoomStability.css';
import './ui/BattleHandExact.css';
import './ui/BattleHandStateAuthority20260830.css';
import './ui/BattleCriticalFixes.css';
import './ui/BattleLayoutPass.css';
import './ui/BattleLayoutFinalOverrides.css';
import './ui/BattleRoomRebuild.css';
import './ui/BattleRoomPolish.css';
import './ui/BattleRoomPolishFinal.css';
import './ui/BattleRoomCardPresentation.css';
import './ui/BattleRoomReferenceFix.css';
import './ui/BattleRoomMirrorCardFix.css';
import './ui/BattleRoomStarAtlasPatch.css';
import './ui/BattleRoomStateGuard.css';
import './ui/BattleRoomToolCompact.css';
import './ui/BattleRoomFinalVisualFix.css';
import './ui/BattlefieldGridRebuild.css';
import './ui/BattlefieldHpAlignment.css';
import './ui/BattleSkillDock.css';
import './ui/BattlefieldViewportFinal.css';
import './ui/BattlefieldFullscreenRepair.css';
import './ui/BattlefieldIceSceneFinal.css';
import './ui/BattlefieldFullscreenFinal.css';
import './ui/BattlefieldReferenceGridFinal.css';
import './ui/BattlefieldMinimalHudFinal.css';
import './ui/MainCityBottomNavFinal.css';
import './ui/BattlefieldCombatPresentationFinal.css';
import './ui/BattleRoomDeckUiV3.css';
import './ui/BattleRoomDeckAtlasV3.css';
import './ui/BattleRoomCardGradeFinal.css';
import './ui/BattlefieldSceneV3Final.css';
import './ui/BattlefieldFrameAlignmentFinal.css';
import './ui/BattlefieldCoordinateAuthorityFinal.css';
import './ui/PvpWildernessRoomFinal.css';
import './ui/PvpWildernessRoomAssetsFinal.css';
import './ui/PvpWildernessDeckEditorFinal.css';
import './ui/PvpAuthoritySyncFinal.css';
import './ui/PvpCombatPolishFinal.css';
import './ui/PvpRound2CoordinateFinal.css';
import './ui/PvpRound3ReferenceFinal.css';
import './ui/ClassicCityChrome.css';
import './ui/BattleChatOverlay.css';
// Final room visual authority: real DOM/CSS only, measured from the 1536×940 reference.
// Legacy 1826 visual tails are deliberately not loaded anymore.
import './ui/BattleRoomReference1536Pixel.css';
// Final card-slot material: transparent glass + supplied lock artwork.
import './ui/BattleHandTransparentFinal20260903.css';
import { installExactBattleRoom } from './ui/BattleRoomExact.js';
import { installBattleRoomFlowPatch } from './ui/BattleRoomFlowPatch.js';
import { installBattleRoomStabilityPatch } from './ui/BattleRoomStabilityPatch.js';
import { installExactBattleHand } from './ui/BattleHandExact.js';
import { installBattleCriticalFixes } from './ui/BattleCriticalFixes.js';
import { installBattleRuntimeFixes } from './ui/BattleRuntimeFixes.js';
import { installBattleLayoutPass } from './ui/BattleLayoutPass.js';
import { installBattleRoomRebuild } from './ui/BattleRoomRebuild.js';
import { installBattleRoomPolish } from './ui/BattleRoomPolish.js';
import { installBattleRoomCardPresentation } from './ui/BattleRoomCardPresentation.js';
import { installBattleRoomStarAtlasPatch } from './ui/BattleRoomStarAtlasPatch.js';
import { installBattleRoomStateGuard } from './ui/BattleRoomStateGuard.js';
import { installBattleRoomModePatch } from './ui/BattleRoomModePatch.js';
import { installBattleRoomDrawerBehaviorFix } from './ui/BattleRoomDrawerBehaviorFix.js';
import { installBattleRoomToolCompact } from './ui/BattleRoomToolCompact.js';
import { installBattleRoomEnemyGeometryFix } from './ui/BattleRoomEnemyGeometryFix.js';
import { installBattlefieldGridRebuild } from './ui/BattlefieldGridRebuild.js';
import { installBattlePvpBarrierSystem } from './ui/BattlePvpBarrierSystem.js';
import { installReferenceSkillDock } from './ui/BattleSkillDock.js';
import { installBattlefieldRuntimeAuditFix } from './ui/BattlefieldRuntimeAuditFix.js';
import { installBattleAttackTimingFix } from './ui/BattleAttackTimingFix.js';
import { installBattleMeleeContactFinal } from './battle/BattleMeleeContactFinal.js';
import { installBattleMushroomProjectileFinal } from './battle/BattleMushroomProjectileFinal.js';
import { installBattleDragCursorCompatibility } from './ui/BattleDragCursorCompatibility.js';
import { installBattlefieldFullscreenRepair } from './ui/BattlefieldFullscreenRepair.js';
import { installBattlefieldFullscreenFinal } from './ui/BattlefieldFullscreenFinal.js';
import { installBattlefieldReferenceGridFinal } from './ui/BattlefieldReferenceGridFinal.js';
import { installBattlefieldMinimalHudFinal } from './ui/BattlefieldMinimalHudFinal.js';
import { installMainCityBottomNavFinal } from './ui/MainCityBottomNavFinal.js';
import { installBattlefieldCombatPresentationFinal } from './ui/BattlefieldCombatPresentationFinal.js';
import { installBattleRoomDeckUiV3 } from './ui/BattleRoomDeckUiV3.js';
import { installBattleRoomDeckResetV4 } from './ui/BattleRoomDeckResetV4.js';
import { installBattleRoomDeckAtlasV3 } from './ui/BattleRoomDeckAtlasV3.js';
import { installBattleRoomReference1826Bridge } from './ui/BattleRoomReference1826Bridge.js';
import { installBattleRoomReference1826Authority } from './ui/BattleRoomReference1826Authority.js';
import { installBattlefieldSceneV3Final } from './ui/BattlefieldSceneV3Final.js';
import { installBattlefieldViewportCanvasFixV3 } from './ui/BattlefieldViewportCanvasFixV3.js';
import { installBattlefieldInputMappingV3 } from './ui/BattlefieldInputMappingV3.js';
import { installBattlefieldLaneFxFinal } from './ui/BattlefieldLaneFxFinal.js';
import { installBattlefieldSkillTargetFinal } from './ui/BattlefieldSkillTargetFinal.js';
import { installBattlefieldCoordinateAuthorityFinal } from './ui/BattlefieldCoordinateAuthorityFinal.js';
import { installBattleHandAvailabilityFinal } from './ui/BattleHandAvailabilityFinal.js';
import { installBattlefieldTransformCompensationFinal } from './ui/BattlefieldTransformCompensationFinal.js';
import { installProjectileViewportFinal } from './ui/ProjectileViewportFinal.js';
import { installPvpWildernessRoomFinal } from './ui/PvpWildernessRoomFinal.js';
import { installPvpBattleBridgeFinal } from './ui/PvpBattleBridgeFinal.js';
import { installPvpAuthoritySyncFinal } from './ui/PvpAuthoritySyncFinal.js';
import { installPvpProjectileSpawnEvent20260819 } from './ui/PvpProjectileSpawnEvent20260819.js';
import { installPvpAuthorityResourceFinal } from './ui/PvpAuthorityResourceFinal.js';
import { installPvpCombatPolishFinal } from './ui/PvpCombatPolishFinal.js';
import { installPvpAnimationContinuityFinal } from './ui/PvpAnimationContinuityFinal.js';
import { installPvpRound2VisualFix } from './ui/PvpRound2VisualFix.js';
import { installPvpImpactFxFinal } from './ui/PvpImpactFxFinal.js';
import { installBossCoopBridgeFinal } from './ui/BossCoopBridgeFinal.js';
import { installBossCoopDiagnostics } from './ui/BossCoopDiagnostics.js';
import { installPvpWildernessDeckEditorFinal } from './ui/PvpWildernessDeckEditorFinal.js';
import { installPvpWildernessRoomDiagnostics } from './ui/PvpWildernessRoomDiagnostics.js';
import { installBattleRound3Rules } from './battle/BattleRound3Rules.js';
import { installPvpRound3ReferenceFinal } from './ui/PvpRound3ReferenceFinal.js';
import { installBattlePointerRound3Compat } from './ui/BattlePointerRound3Compat.js';
import { installBattleCardFeedbackFinal } from './ui/BattleCardFeedbackFinal.js';
import { installBattleCardTraitFxFinal } from './ui/BattleCardTraitFxFinal.js';
import { installBattleSkillInteractionFinal } from './ui/BattleSkillInteractionFinal.js';
import { installBattleStatusFxPerformanceFinal } from './ui/BattleStatusFxPerformanceFinal.js';
import { installBattleHealingFeedbackFinal } from './ui/BattleHealingFeedbackFinal.js';
import { installBattleSkillVisualLifetimeFinal } from './ui/BattleSkillVisualLifetimeFinal.js';
import { installBattlefieldRuntimeCoordinateFinal } from './ui/BattlefieldRuntimeCoordinateFinal.js';
import { installBattleSkillPositionFinal } from './ui/BattleSkillPositionFinal.js';
import { installBattleImpactSafetyFinal } from './ui/BattleImpactSafetyFinal.js';
import { installBattleUnitHaloFinal } from './ui/BattleUnitHaloFinal.js';
import { installUnitAnimationViewportFinal } from './ui/UnitAnimationViewportFinal.js';
import { installBattlePresentationCompletion20260811 } from './ui/BattlePresentationCompletion20260811.js';
import { installBattleRuleConvergence20260830 } from './battle/BattleRuleConvergence20260830.js';
import { installBattleTalentAuthority20260830 } from './ui/BattleTalentAuthority20260830.js';
import { schedulePvpProjectileContinuity20260819 } from './ui/PvpProjectileContinuity20260819.js';
import { installBattleUserRules20260903 } from './battle/BattleUserRules20260903.js';
import { installBattleUserPresentation20260903 } from './ui/BattleUserPresentation20260903.js';
import { installBattleChatOverlay } from './ui/BattleChatOverlay.js';
import { installBattleCraftMaterialDrops20260905 } from './battle/BattleCraftMaterialDrops20260905.js';
import { installGuildWarehouseGridPatch } from './ui/GuildWarehouseGridPatch.js';
import { installAuctionGridPatch } from './ui/AuctionGridPatch.js';
import { installSystemAnnouncementClient } from './ui/SystemAnnouncementClient.js';
import { RoomUtilityOverlay } from './ui/RoomUtilityOverlay.js';
import { App } from './ui/App.js';

installBattleRoomFlowPatch();
installBattleRoomStabilityPatch();
installExactBattleRoom();
installExactBattleHand();
installBattleCriticalFixes();
installBattleRuntimeFixes();
installBattleLayoutPass();
installBattleRoomRebuild();
installBattleRoomPolish();
installBattleRoomCardPresentation();
installBattleRoomStarAtlasPatch();
installBattleRoomStateGuard();
installBattleRoomModePatch();
installBattleRoomDrawerBehaviorFix();
installBattleRoomToolCompact();
installBattleRoomEnemyGeometryFix();
installBattlefieldGridRebuild();
installBattlePvpBarrierSystem();
installReferenceSkillDock();
installBattlefieldRuntimeAuditFix();
installBattleAttackTimingFix();
installBattleMeleeContactFinal();
installBattleMushroomProjectileFinal();
installBattleDragCursorCompatibility();
installBattlefieldFullscreenRepair();
installBattlefieldFullscreenFinal();
installBattlefieldReferenceGridFinal();
installBattlefieldMinimalHudFinal();
installMainCityBottomNavFinal();
installBattlefieldCombatPresentationFinal();
installBattleRoomDeckUiV3();
installBattleRoomDeckResetV4();
installBattleRoomDeckAtlasV3();
installBattleRoomReference1826Bridge();
installBattlefieldSceneV3Final();
installBattlefieldViewportCanvasFixV3();
installBattlefieldInputMappingV3();
installBattlefieldLaneFxFinal();
installBattlefieldSkillTargetFinal();
installBattlefieldCoordinateAuthorityFinal();
installBattleHandAvailabilityFinal();
installBattlefieldTransformCompensationFinal();
installProjectileViewportFinal();
installPvpWildernessRoomFinal();
installPvpBattleBridgeFinal();
installPvpAuthoritySyncFinal();
installPvpProjectileSpawnEvent20260819();
installPvpAuthorityResourceFinal();
installPvpCombatPolishFinal();
installPvpAnimationContinuityFinal();
installPvpRound2VisualFix();
installPvpImpactFxFinal();
installBossCoopBridgeFinal();
installBossCoopDiagnostics();
installPvpWildernessDeckEditorFinal();
installPvpWildernessRoomDiagnostics();
installBattleRound3Rules();
installPvpRound3ReferenceFinal();
installBattlePointerRound3Compat();
installBattleCardFeedbackFinal();
installBattleCardTraitFxFinal();
installBattleSkillInteractionFinal();
installBattleStatusFxPerformanceFinal();
installBattleHealingFeedbackFinal();
installBattleSkillVisualLifetimeFinal();
installBattlefieldRuntimeCoordinateFinal();
installBattleSkillPositionFinal();
installBattleImpactSafetyFinal();
installBattleUnitHaloFinal();
installUnitAnimationViewportFinal();
installBattlePresentationCompletion20260811();
installBattleRuleConvergence20260830();
installBattleTalentAuthority20260830();
schedulePvpProjectileContinuity20260819();
// Final geometry authority runs after every legacy room/PVP runtime patch.
installBattleRoomReference1826Authority();
// User battle-rule authority must be last: permanent peach flight/death VFX + phantom air-death summon.
installBattleUserRules20260903();
installBattleUserPresentation20260903();
installBattleChatOverlay();

// 2026-09-05 economy / announcement / loot completion patches.
installBattleCraftMaterialDrops20260905();
installGuildWarehouseGridPatch();
installAuctionGridPatch();
installSystemAnnouncementClient();

const app = new App(document.getElementById('app'));
const roomUtilityOverlay = new RoomUtilityOverlay(app);
roomUtilityOverlay.install();
app.mount();